parser: babel-eslint
env:
  browser: true
  commonjs: true
  es6: true
  mocha: true
extends:
  - 'eslint:recommended'
  - 'plugin:flowtype/recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
  sourceType: module
plugins:
  - flowtype
rules:
  'flowtype/space-after-type-colon':
    - error
    - never
  'flowtype/space-before-type-colon':
    - error
    - always
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-lone-blocks:
    - error
  no-unused-expressions:
    - error
  eol-last:
    - error
    - always

  # Commas
  comma-dangle:
    - error
    - always-multiline
  comma-spacing:
    - error
    -
      before: false
      after: true
  comma-style:
    - error
    - last

  # Variables
  no-shadow:
    - error
  no-var:
    - error
  prefer-const:
    - error
  prefer-destructuring:
    - error
  prefer-rest-params:
    - error
  prefer-spread:
    - error

  # Line breaks
  linebreak-style:
  - error
  - unix

  # if blocks
  no-else-return:
    - error

  # Imports
  no-duplicate-imports:
    - error

  # Functions
  prefer-arrow-callback:
    - error
  arrow-parens:
    - error
    - as-needed
    -
      requireForBlockBody: true

  # Whitespace
  no-multi-spaces:
    - error
  no-whitespace-before-property:
    - error
  object-curly-spacing:
    - error
    - always
  no-trailing-spaces:
    - error
  space-before-blocks:
    - error
    - always
  space-before-function-paren:
    - error
    - never
  spaced-comment:
    - error
    - always
  block-spacing:
    - error
    - always
  arrow-spacing:
    - error
    -
      before: true
      after: true
